### ISSUE TITLE
Limit on wsuwp_json feed

### ISSUE THREAD

**Issue by clintyoung** [washingtonstateuniversity/WSUWP-Content-Syndicate#26]
Please put a comment by count so we know that the max default without a count is 10.

Example:
public function display_wsuwp_json( $atts ) {
		$defaults = array(
			'object' => 'json_data',
			'output' => 'json', // Can also be headlines, excerpts, or full
			'host' => 'news.wsu.edu',
			'site' => '',
			'university_category_slug' => '',
			'site_category_slug' => '',
			'tag' => '',
			'query' => 'posts',
			'local_count' => 0,
			'count' => false, //defaults to 10 max if not used
			'date_format' => 'F j, Y',
			'offset' => 0,
			'cache_bust' => '',
		);

**Comment by jeremyfelt** [comment]
Documented in 7c85bf3cbb0b5c4e0, though not as 10 as it defaults to the `posts_per_page` setting of the remote site.
